### PR TITLE
Github actions improvements, replace outdated libraries

### PR DESCRIPTION
**Pull request by indy2kro**
This pull request contains quite a lot of changes (probably would be better with several requests, but don't have the time to do it one by one):

- Added multiple Github actions pipelines for each Laravel version supported (with supported PHP versions)
- Bumped Node.js version in Github actions to 20 (including actions/setup-node@v4, actions/checkout@v4, actions/cache@v4)
- Replaced set-output syntax (deprecated)
- Updated package-lock.json with more recent versions
- Replaced nunomaduro/larastan (deprecated) with larastan/larastan
- Updated phpunit.xml to latest format
- Replaced pestphp/pest-plugin-mock (deprecated) with Mockery
- Fixed GitHelperTest.php test when running on more recent version of git

The last issue caused the test to fail when running on git 2.43 (also depends on push.autoSetupRemote configuration):
```
fatal: The current branch test-branch has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream test-branch test-branch

To have this happen automatically for branches without a tracking
upstream, see 'push.autoSetupRemote' in 'git help config'.
```

### CODE REVIEW

**Comment by igorsgm** [comment]
LGTM! Thanks for your contribution @indy2kro. 

These were great additions! Merged and released in `v1.3.0`

**Comment by indy2kro** [comment]
The release currently contains some parameters which were meant to be implemented, but the functionality is not yet there, I will make next week another pull request with the full functionality (WIP) - If you are not ok with that functionality, the config parameters can be removed.

**Comment by igorsgm** [comment]
Sounds good @indy2kro . I’ll be waiting for your PR, thanks

**Comment by indy2kro** [comment]
@igorsgm I think you merged also the changes to README.md with indy2kro/laravel-git-hooks package name, those will need to be reverted, otherwise should be fine.

**Pull request merged**
